name: Deployment
on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build-npm-test.yml
  npm:
    needs: build
    uses: ./.github/workflows/publish-npm.yml
    secrets:
      PUBLISH_NPM_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
  gpr:
    needs: build
    uses: ./.github/workflows/publish-gpr.yml
    secrets:
      PUBLISH_GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  paydevs:
    needs: build
    uses: ./.github/workflows/publish-paydevs.yml
    secrets:
      PUBLISH_PAYDEVS_USERNAME: ${{ secrets.PUBLISH_PAYDEVS_USERNAME }}
      PUBLISH_PAYDEVS_PASSWORD: ${{ secrets.PUBLISH_PAYDEVS_PASSWORD }}
      PUBLISH_PAYDEVS_EMAIL: ${{ secrets.PUBLISH_PAYDEVS_EMAIL }}
